Hw3
made-mlops-2022/Safonov_Fedor pull request #3
Opened 2022-12-04 20:36 UTC by superAIyah

**Основная часть:**

- Поднимите airflow локально, используя docker compose. 

- Реализуйте dag, который генерирует данные для обучения модели **(5 баллов)**

- Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день. **(10 баллов)** 

- Реализуйте dag, который использует модель ежедневно **(5 баллов)**

- все даги реализованы только с помощью DockerOperator  **(10 баллов)**

- Традиционно, самооценка **(1 балл)**

*Дополнительно:*

- Реализованы сенсоры на то, что данные готовы для дагов тренировки и обучения **(3 доп балла)**

**Сумма:**

*34 балла*

**Скрины:**
![image](https://user-images.githubusercontent.com/90476839/205514083-5c8c06bc-28bb-4d1e-a807-394512863c99.png)
![image](https://user-images.githubusercontent.com/90476839/205514097-bd16840c-9b17-48da-890a-24fb122396b0.png)
![image](https://user-images.githubusercontent.com/90476839/205514106-0e87cab2-ead2-473b-829a-168f5232ab7b.png)
![image](https://user-images.githubusercontent.com/90476839/205514121-61d49712-8acc-4368-8cc9-8be6ed4aa26a.png)

2022-12-07 08:50 UTC, bulaevvi requested changes
В задании указано: "Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в исполненном без ошибок виде) и прикрепите их в описание пулл реквеста". У Вас приведен только один кондиционный скриншот. См. пример правильного оформления в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-07 10:25 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-07 20:12 UTC, superAIyah commented
> Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

Да, конечно:
![image](https://user-images.githubusercontent.com/90476839/206285229-937639dd-11a5-432b-83fc-10d97d3dd1da.png)
![image](https://user-images.githubusercontent.com/90476839/206285600-74bc0bf5-65b0-4c36-9944-8c49db218818.png)
![image](https://user-images.githubusercontent.com/90476839/206285444-f7932b90-1481-47cd-a62e-f4e7cd72fdda.png)
![image](https://user-images.githubusercontent.com/90476839/206285503-34db76c3-266b-4824-81d3-3e6162756173.png)

2022-12-08 04:38 UTC, bulaevvi approved these changes
Итого 34 балла. Делайте merge

2022-12-08 13:10 UTC, merged